### ISSUE TITLE
Setup Travis-CI for the project

### ISSUE THREAD

**Issue by pamuditha** [CodeLanka/ElePath-Ruby#10]

**Comment by sjha2048** [comment]
hey @pamuditha, can I try it?

**Comment by pamuditha** [comment]
@sjha2048  yes you can

**Comment by zhmurko** [comment]
@sjha2048 any progress on this?

**Comment by isuruAb** [comment]
@sjha2048  are you still working on this ?

@zhmurko  can you try this out ?

**Comment by zhmurko** [comment]
@isuruAb yes, will do
