### ISSUE TITLE
Fix Licensing Issues

### ISSUE THREAD

**Issue by pamuditha** [CodeLanka/ElePath-Ruby#20]

**Comment by manik1235** [comment]
What licensing issues do you need fixed?

**Comment by iennae** [comment]
![screen shot 2018-10-16 at 7 43 26 pm](https://user-images.githubusercontent.com/1592404/47058872-cd478880-d17b-11e8-8b16-7767999f554b.png)

It's not clear what licensing issues are present that you want fixed.

**Comment by pamuditha** [comment]
already fixed it :-)
